### ISSUE TITLE
JustifiedGallery not working with jQuery 3.7.1

### ISSUE THREAD

**Issue by derWebdesigner** [miromannino/Justified-Gallery#398]
I had the error `$jg.justifiedGallery is not a function` for hours now and I simply couldn't find out why. What actually helped is using `npm ls jquery justifiedGallery` which showed a version mismatch that resulted in multiple jQuery versions being used. For whatever reason justifiedGallery is the only package that specifically uses jquery@3.7.0. When I install this specific version everything finally works again, so I wonder if there is a dependency in this package that prevents 3.7.1.

Thank you for this awesome package, I highly appreciate your efforts.

**Comment by miromannino** [comment]
Version v4.0.0 doesn't use JQuery anymore, this shouldn't be a problem anymore

**Comment by derWebdesigner** [comment]
> Version v4.0.0 doesn't use JQuery anymore, this shouldn't be a problem anymore

Sounds awesome. Thank you for the hint about the new release; I can't wait to give it a try.
